### ISSUE TITLE
TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by let4be** [gilt/postcss-less#5]
```
Module build failed: TypeError: Cannot read property 'parse' of undefined
    at new LazyResult (/home/dev/projects/vv-video/node_modules/postcss/lib/lazy-result.js:58:23)
    at Processor.process (/home/dev/projects/vv-video/node_modules/postcss/lib/processor.js:34:16)
    at Object.riot.parsers.js.es6.riot.parsers.css.cssnext.riot.parsers.css.less (/home/dev/projects/vv-video/src/riot.loader.js:20:28)
    at _compileCSS (/home/dev/projects/vv-video/node_modules/riot-compiler/lib/compiler.js:540:30)
    at cssCode (/home/dev/projects/vv-video/node_modules/riot-compiler/lib/compiler.js:792:10)
    at /home/dev/projects/vv-video/node_modules/riot-compiler/lib/compiler.js:914:47
    at String.replace (native)
    at /home/dev/projects/vv-video/node_modules/riot-compiler/lib/compiler.js:912:23
    at String.replace (native)
    at Object.compile (/home/dev/projects/vv-video/node_modules/riot-compiler/lib/compiler.js:885:6)
    at Object.riot.parsers.js.es6.riot.parsers.css.cssnext.riot.parsers.css.less.module.exports (/home/dev/projects/vv-video/src/riot.loader.js:24:14)
 @ ./src/app/index.js 23:0-30
```

**Comment by shellscape** [comment]
This project is not being actively maintained at the moment. Should that change, I'll follow up on this issue. For now, we recommend https://github.com/webschik/postcss-less
